### ISSUE TITLE
En tant qu'adhérent du LICA, je veux pouvoir m'inscrire sur LS

### ISSUE THREAD

**Issue by Meknassih** [draden05/LICAsphere_FRONT#19]
- [x] Vérifier que l'utilisateur est un adhérent du LICA grâce à l'API d'HelloAsso
- [x] Proposer un formulaire dans une prochaine étape : 
  - Prénom
  - Nom
  - Localisation géoraphique
  - E-mail
  - Mot de passe
  - Case à cocher "J'accepte les conditions d'utilisations de LicaSphère"

**Comment by draden05** [comment]
Closed by 75995e8
